if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall | source $MYVIMRC
endif


call plug#begin('~/.vim/plugged')

Plug 'kien/ctrlp.vim'
Plug 'tomasr/molokai'
Plug 'kien/tabman.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'majutsushi/tagbar'
Plug 'scrooloose/nerdtree'

Plug 'bling/vim-airline' | Plug 'ryanoasis/vim-devicons'

call plug#end()



set number

set scrolloff=6

set hlsearch


"" highlight tabs
set list
set listchars=tab:→\ 
nmap <leader>l :exec &listchars == "tab:  " ? "set listchars=tab:→\\ " : "set listchars=tab:\\ \\ "<CR>


"" Syntax highlithing
syntax on
filetype plugin on
filetype plugin indent off


"" Color scheme
let g:rehash256 = 1
colorscheme molokai


"" 80 colums margin
vertical resize 81
set colorcolumn=81


"" For vimdiff
if &diff
	colorscheme elflord
endif


"" NERDTree
map <F5> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif


"" Highlight lines
set cursorline
map <F10> :set cursorcolumn!<Bar>set cursorline!<CR>


"" vim-airline
set laststatus=2
let g:airline_theme='light'
let g:airline_powerline_fonts = 1


"" Tagbar
nmap <F7> :TagbarToggle<CR>


"" Tabman
let g:tabman_toggle = '<F6>'


"" Nicer window movement key bindings
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


set fillchars+=vert:\ 
hi vertsplit ctermbg=fg


"" Don't close buffer when opening new one "over" another one
set hidden


"" https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally
set splitbelow
set splitright


"" Make file "unix like"
map <F9> :set fileencoding=utf-8<CR>:set ff=unix<CR>


"" Wrap cursor on line endings
set whichwrap+=<,>,h,l,[,]


"" Indenting
"" http://stackoverflow.com/a/7413117
set tabstop=4
set shiftwidth=4

set copyindent
set preserveindent

inoremap <CR> <CR>x<BS>
nnoremap o ox<BS>
nnoremap O Ox<BS>


"" Save with ctrl + s
"" https://bbs.archlinux.org/viewtopic.php?id=140902
"" http://vim.wikia.com/wiki/Map_Ctrl-S_to_save_current_or_new_files
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>



