#!/bin/sh

xrdb -merge ~/.Xresources
urxvtd -q -f -o &
dex -a -e i3 &


if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		case "$f" in
			*dbus*)
			;;
			*)
				[ -x "$f" ] && . "$f"
			;;
		esac
	done
fi
