#!/bin/sh

xrdb -merge ~/.Xresources
urxvtd -q -f -o &
nm-applet &
xmodmap ~/.Xmodmap
sc auto

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi
