#!/bin/bash

set -e

call() {
	if ! "$@" ; then
		ret="$?"
		echo "$@" >&2
		echo "Execution failed with exit code $ret." >&2
		exit $?
	fi
}


iptx() {
	ipt4 "$@"
	ipt6 "$@"
}


ipt4() {
	call iptables "$@"
}


ipt6() {
	call ip6tables "$@"
}


cgcreate -g net_cls:fullnet
echo 0x00420001 > /sys/fs/cgroup/net_cls/fullnet/net_cls.classid
chmod 660 /sys/fs/cgroup/net_cls/fullnet/tasks
chown root:fullnet /sys/fs/cgroup/net_cls/fullnet/tasks

## watch -d -n 2 iptables  -nvL
## Nice approach: https://www.digitalocean.com/community/tutorials/how-to-list-and-delete-iptables-firewall-rules
## Can be used for home net detection: http://www.netfilter.org/documentation/HOWTO/netfilter-extensions-HOWTO-3.html#ss3.2
## cgroups: http://habrahabr.ru/post/274445/

##    22/TCPx: SSH
##    67/UDP4: DHCP Server
##    68/UDP4: DHCP Client
## 22000/TCPx: syncthing (data)
## 22067/TCPx: syncthing (relay)
## 21027/UDPx: syncthing (broadcast)
##    80/TCPx: HTTP
##   443/TCPx: HTTPS
##   993/TCPx: IMAPS
##   465/TCPx: SMTPS
##  5222/TCPx: XMPP
##   631/TCPx: IPP
##  9100/TCPx: HP JetDirect
##    43/TCPx: Who is
##    53/UDPx: DNS
##    53/TCPx: DNS
##   123/UDPx: NTP
##  9418/TCPx: Native GIT
##   873/TCPx: Rsync
##  5353/UDPx: Avahi
##   137/UDPx: NetBios Name Service
##   138/UDPx: NetBios Datagram
## 19375/UDPx: "whoisthere"
##  3632/TCPx: DistCC
## 64738/TCPx: Mumble control
## 64738/UDPx: Mumble speach
## DHCP seems to use raw sockets, which can't be filtered


iptx -Z


## == Table: mangle
iptx -t mangle -F
iptx -t mangle -X
iptx -t mangle -P PREROUTING ACCEPT
iptx -t mangle -P INPUT ACCEPT
iptx -t mangle -P FORWARD ACCEPT
iptx -t mangle -P OUTPUT ACCEPT
iptx -t mangle -P POSTROUTING ACCEPT


## == Table: nat
ipt4 -t nat -F
ipt4 -t nat -X
ipt4 -t nat -P PREROUTING ACCEPT
ipt4 -t nat -P INPUT ACCEPT
ipt4 -t nat -P OUTPUT ACCEPT
ipt4 -t nat -P POSTROUTING ACCEPT


## == Table: filter
iptx -F
iptx -X
iptx -P INPUT DROP
iptx -P FORWARD DROP
iptx -P OUTPUT DROP

# iptx -P INPUT ACCEPT
# iptx -P FORWARD ACCEPT
# iptx -P OUTPUT ACCEPT
# exit 0

iptx -N IN_LOG
iptx -N OUT_LOG

## === INPUT
## ==== Accept canonical
iptx -A INPUT -i lo -j ACCEPT
ipt4 -A INPUT -p igmp -j ACCEPT
ipt4 -A INPUT -p icmp -j ACCEPT
ipt6 -A INPUT -p ipv6-icmp -j ACCEPT

## ==== Accept special ports
## TCP (simple)
iptx -A INPUT -p tcp -m multiport --dports 22,22000,3632 -j ACCEPT

## UDP (simple)
iptx -A INPUT -p udp -m multiport --dports 21027 -j ACCEPT

## DHCP (why isn't conntrack sufficient?)
ipt6 -A INPUT -p udp --sport 547 --dport 546 -j ACCEPT

## Avahi
ipt4 -A INPUT -p udp --dport 5353 -d 224.0.0.251 -j ACCEPT
ipt6 -A INPUT -p udp --dport 5353 -d ff02::fb -j ACCEPT

## Existing connections
iptx -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

## ==== Reject remaining
## Log
iptx -A INPUT -j IN_LOG

## Reject TCP
iptx -A INPUT -p tcp -j REJECT --reject-with tcp-reset

## Reject UDP
ipt4 -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
ipt6 -A INPUT -p udp -j REJECT --reject-with icmp6-port-unreachable

## Reject Remaining
ipt4 -A INPUT -j REJECT --reject-with icmp-proto-unreachable
ipt6 -A INPUT -j REJECT

## === IN_LOG
## Log filter
iptx -A IN_LOG -m pkttype ! --pkt-type unicast -j RETURN

## Log
iptx -A IN_LOG -m limit --limit 10/min -j LOG --log-prefix "iptables: Reject IN: " --log-level 7



## === OUTPUT
## ==== Accept canonical
iptx -A OUTPUT -o lo -j ACCEPT
ipt4 -A OUTPUT -p igmp -j ACCEPT
ipt4 -A OUTPUT -p icmp -j ACCEPT
ipt6 -A OUTPUT -p ipv6-icmp -j ACCEPT

## ==== Accept special ports
## TCP (simple)
iptx -A OUTPUT -p tcp -m multiport --dports 22,80,443,993,465,5222,631,22000,22067,43,873,9418,64738,9100 -j ACCEPT

## UDP (simple)
iptx -A OUTPUT -p udp -m multiport --dports 123,60001:60999,64738 -j ACCEPT

## DHCP
ipt4 -A OUTPUT -p udp --sport 68 --dport 67 -j ACCEPT
ipt6 -A OUTPUT -p udp --sport 546 --dport 547 -j ACCEPT

## TCP and UDP
for p in udp tcp ; do
	## Allow only unbound, who checks DNSSEC records, to do DNS queries
	iptx -A OUTPUT -p $p -m owner --uid-owner $(id -u unbound) --dport 53 -j ACCEPT
done

## Existing connections
iptx -A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

## Started by "fullnet"
iptx -A OUTPUT -m cgroup --cgroup 0x00420001  -j ACCEPT

## ==== Reject remaining
## Log
iptx -A OUTPUT -j OUT_LOG

## Reject TCP
iptx -A OUTPUT -p tcp -j REJECT --reject-with tcp-reset

## Reject UDP
ipt4 -A OUTPUT -p udp -j REJECT --reject-with icmp-port-unreachable
ipt6 -A OUTPUT -p udp -j REJECT --reject-with icmp6-port-unreachable

## Reject Remaining
ipt4 -A OUTPUT -j REJECT --reject-with icmp-proto-unreachable
ipt6 -A OUTPUT -j REJECT

## === OUT_LOG
## Log
iptx -A OUT_LOG -m limit --limit 10/min -j LOG --log-prefix "iptables: Reject OUT: " --log-level 7
