#!/bin/sh

set -e

## Install everything using one if the following methods
## curl -s https://raw.githubusercontent.com/Skrupellos/dotfiles/master/share/bootstrap-via-https | sh
## wget -O - https://raw.githubusercontent.com/Skrupellos/dotfiles/master/share/bootstrap-via-https | sh

git clone https://github.com/Skrupellos/dotfiles.git
cd dotfiles
git submodule init
git submodule update

exec bin/dotinstall