#!/bin/sh

set -e

## Install everything using
## wget -O - https://raw.githubusercontent.com/Skrupellos/dotfiles/master/share/bootstrap-via-ssh | sh

git clone ssh://git@github.com/Skrupellos/dotfiles.git

exec dotfiles/bin/dotinstall