#!/bin/sh

set -e

## Install everything using
## wget -O - https://raw.githubusercontent.com/Skrupellos/dotfiles/master/share/bootstrap-via-https | sh

git clone https://github.com/Skrupellos/dotfiles.git

exec dotfiles/bin/dotinstall