#!/bin/bash

## non-interactive shells shall not pass
case "$-$DOT_FAKE_DASH" in
	*i*)
	;;
	*)
		return
	;;
esac


## ==== Variable definitions ===================================================
## -- Actual shell ($SHELL is the login shell)
S_ACT_SHELL="$(ps -p $$ -o comm=)"

## -- hostname is not everywhere installed, therefore we need our own
S_FQDN="$(cat /proc/sys/kernel/hostname)"
S_HOST="$(cut -d. -f1 /proc/sys/kernel/hostname)"
S_DOMAIN="$(cut -d. -f2- /proc/sys/kernel/hostname)"

## -- test for login shell
case "$S_ACT_SHELL" in
	"bash")
		if shopt -q login_shell
		then S_LOGIN="y"
		else S_LOGIN="n"
		fi
		;;
	"zsh")
		if [[ -o login ]]
		then S_LOGIN="y"
		else S_LOGIN="n"
		fi
		
		if [ -f /etc/zsh/zprofile ] ; then . /etc/zsh/zprofile ; fi
		if [ -f /etc/zsh/zshrc ] ; then . /etc/zsh/zshrc ; fi
		if [ -f /etc/zsh/zlogin ] ; then . /etc/zsh/zlogin ; fi
		
		setopt NO_RCS
		;;
	*)
		S_LOGIN="y"
		;;
esac


## ==== Once on all interactive shells (variables, umask) ======================
if [ -z "$DOT_DIR" ] ; then
	if [ -f "$HOME/.dot/dir" ] ; then
		export DOT_DIR="$(cat "$HOME/.dot/dir")"
		export PATH="$DOT_DIR/bin:$PATH"
	else
		return
	fi
	
	for f in "$DOT_DIR/share/variables-sh_"* ; do
		. "$f"
	done
	
	case "$S_DOMAIN" in
		"fs.lmu.de"|*".fs.lmu.de")
			umask 0007
			;;
		"cip.ifi.lmu.de")
			umask 0077
			;;
		*)
			umask 0022
			;;
	esac
fi


## ==== Every time on all interactive shells (aliases, functions) ==============
case "$S_DOMAIN" in
	"cip.ifi.lmu.de")
		unalias rm
		;;
esac

for f in \
	"$DOT_DIR/share/aliases_"* \
	"$DOT_DIR/share/promt-sh_"*
do
	. "$f"
done

case "$S_ACT_SHELL" in
	"bash")
		# check the window size after each command and, if necessary,
		# update the values of LINES and COLUMNS.
		shopt -s checkwinsize
		
		# Prevent that multiple bash instances overwrite the readline history of each
		# other.
		shopt -s histappend
		;;
	
	"zsh")
		## khome = Home   kcuu1 = Up      kpp = Page Up
		## kend  = End    kcud1 = Down    knp = Page Down
		## kich1 = Ins    kcub1 = Left
		## kdch1 = Del    kcuf1 = Right
		
		# setup key accordingly
		test -n "${terminfo[khome]}" && bindkey "${terminfo[khome]}"   beginning-of-line
		test -n "${terminfo[kend]}"  && bindkey "${terminfo[kend]}"    end-of-line
		test -n "${terminfo[kich1]}" && bindkey "${terminfo[kich1]}"   overwrite-mode
		test -n "${terminfo[kdch1]}" && bindkey "${terminfo[kdch1]}"   delete-char
		test -n "${terminfo[kcub1]}" && bindkey "${terminfo[kcub1]}"   backward-char
		test -n "${terminfo[kcuf1]}" && bindkey "${terminfo[kcuf1]}"   forward-char
		test -n "${terminfo[kpp]}"   && bindkey "${terminfo[kpp]}"     beginning-of-buffer-or-history
		test -n "${terminfo[knp]}"   && bindkey "${terminfo[knp]}"     end-of-buffer-or-history
		test -n "${terminfo[kcuf1]}" && bindkey "\e${terminfo[kcuf1]}" forward-word
		test -n "${terminfo[kcub1]}" && bindkey "\e${terminfo[kcub1]}" backward-word
		test -n "${terminfo[kcuu1]}" && bindkey "${terminfo[kcuu1]}"   up_line_or_local_history
		test -n "${terminfo[kcud1]}" && bindkey "${terminfo[kcud1]}"   down_line_or_local_history
		                                bindkey "^[Oa"  up-line-or-history
		                                bindkey "^[Ob"  down-line-or-history
		
		## Open man page for current command
		#bindkey "^X^H" run-help
		
		
		# Finally, make sure the terminal is in application mode, when zle is
		# active. Only then are the values from $terminfo valid.
		if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} ))
		then
			zle_line_init() {
				printf '%s' "${terminfo[smkx]}"
			}
			
			zle_line_finish() {
				printf '%s' "${terminfo[rmkx]}"
			}
			
			zle -N zle_line_init
			zle -N zle_line_finish
		fi
		
		
		up_line_or_local_history() {
			zle set-local-history 1
			zle up-line-or-history
			zle set-local-history 0
		}
		zle -N up_line_or_local_history
		
		down_line_or_local_history() {
			zle set-local-history 1
			zle down-line-or-history
			zle set-local-history 0
		}
		zle -N down_line_or_local_history
		
		
		setopt share_history
		setopt hist_ignore_all_dups
		setopt autocd
		setopt extendedglob
		setopt notify                 ## Immediate satus update of jobs
		
		autoload -U compinit
		compinit
		
		## Add a caption with the source of the suggestions
		zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
		zstyle ':completion:*:warnings'     format '%BSorry, no matches for: %d%b'
		
		## Color directory suggestions
		zstyle ':completion:*:default'      list-colors ${(s.:.)LS_COLORS}
		;;
esac


## ==== Every time on interactive login shells =================================
if [ "$S_LOGIN" = "y" ]
then
	## -- Start D-Bus ----------------------------------------------------------
	if \
		[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && \
		[ -n "$DISPLAY" ] && \
		type dbus-launch >/dev/null 2>&1
	then
		eval $(dbus-launch --exit-with-session | tee /tmp/buuuus)
		export DBUS_SESSION_BUS_ADDRESS
		export DBUS_SESSION_BUS_PID
		export DBUS_SESSION_BUS_WINDOWID
	fi
	
	## -- Start key agents -----------------------------------------------------
	
	if type gnome-keyring-daemon >/dev/null 2>&1 && [ -n "$DISPLAY" ]
	then
		eval "$(gnome-keyring-daemon --start)"
		export GNOME_KEYRING_CONTROL
		export SSH_AUTH_SOCK
		export GPG_AGENT_INFO
	elif type gpg-agent >/dev/null 2>&1 && [ -n "$DISPLAY" ]
	then
		if [ -f "$HOME/.gpg-agent-info" ] ; then
			. "$HOME/.gpg-agent-info"
			
			if [ ! -O "$SSH_AUTH_SOCK" ] ; then
				unset SSH_AUTH_SOCK
			fi
		fi
		
		if [ -z "$SSH_AUTH_SOCK" ] ; then
			gpg-agent --daemon --enable-ssh-support >"$HOME/.gpg-agent-info"
			. "$HOME/.gpg-agent-info"
		fi
	elif type ssh-agent >/dev/null 2>&1 
	then
		ssh-agent >"$HOME/.ssh-agent-info"
		. "$HOME/.ssh-agent-info"
	fi

## ==== Every time on interactive non-login shells =============================
else
	true
fi
